version: '3'  

services:
  web:
    image: nginx  
    ports:
      - "80:80" 
    volumes:
      - ./html:/usr/share/nginx/html  

  app:
    image: basak-app 1.0
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=True  

  db:
    image: postgres:latest  
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
